---
- name: Check which plugins are installed
  command: "ls {{ grafana_data_dir }}/plugins"
  # find:
  #   file_type: directory
  #   recurse: false
  #   paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- set_fact:
    grafana_plugins:  "{{ grafana_plugins | difference(installed_plugins.stdout_lines) }}"

- debug:
    var: installed_plugins

- name: Install plugins
  become: true
  command: "grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart {{ service_name }}
  when: grafana_plugins is defined