---

- name: Download gpg key
  get_url:
    url: https://packages.grafana.com/gpg.key
    dest: "{{ item.sslcacert }}"
  with_items: {{ yum_repository }}

- name: Add {{ service_name }} repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}" YUM repo
    baseurl: "{{ item.baseurl }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    sslverify: "{{ item.sslverify }}"
    sslcacert: "{{ item.sslcacert }}"
  with_items: {{ yum_repository }}

- name: Ensure package idependent are installed.
  yum:
    name: "{{ yum_packages_name }}"
    update_cache: true
    state: present

- name: Ensure {{ service_name }} are installed.
  yum:
    name: "{{ packages_name }}"
    update_cache: true
    state: present
